### ISSUE TITLE
mock https failed?

### ISSUE THREAD

**Issue by mansonami** [falconry/falcon-require-https#10]
192.168.8.116 - - [08/Jul/2020 18:29:34] code 400, message Bad request syntax ('\x16\x03\x01\x00å\x01\x00\x00á\x03\x03¤kÖYàÚÒW\\ý\x1d\xad\x1dÝ3÷{$\x98\x14c\\\x96µ\x83Y>__\x1c\x07~ aýëÈÿ¶ìþ\x9fÖX¹áã\x0cÝÓ\x81wÈ+\x85\x05×@\x0e\x7féªl½K\x00$\x13\x01\x13\x02\x13\x03À/À+À0À,Ì©Ì¨À\tÀ\x13À')
192.168.8.116 - - [08/Jul/2020 18:29:34] "åá¤kÖYàÚÒW\ý­Ý3÷{$c\µY>__~ aýëÈÿ¶ìþÖX¹áã
                                                                                      ÝÓwÈ+×@éªl½K$À/À+À0À,Ì©Ì¨À	ÀÀ" 400 -

Error: write EPROTO 140672120418856:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

**Comment by vytas7** [comment]
Hi @mansonami !
Sorry to be blunt, but I don't really see your issue as being whatsoever related to the Falcon framework, or this `falcon-require-https` add-on.

It looks like your issues are stemming from your TLS stack, which seems to be based on [BoringSSL](https://github.com/google/boringssl) (are you by chance on a Chromebook?). BoringSSL states explicitly that:
> Although BoringSSL is an open source project, it is not intended for general use, as OpenSSL is. We don't recommend that third parties depend upon it. Doing so is **likely to be frustrating** because there are no guarantees of API or ABI stability.

(emphasis mine :arrow_up: )

I'm going to close this issue, since we simply can not do anything inside Falconry projects to address the underlying problem.

If possible, try to install and run your Python stack using OpenSSL, as AFAICT it is the only SSL library flavour it supports.
Good luck!

**Comment by vytas7** [comment]
Or is that BoringSSL error coming from another tool (or the Chrome browser) when trying to access your server?

If that was the case, it could be that you were simply trying to access an HTTP server over HTTPS.
`falcon-require-https` cannot turn your HTTP server into HTTPS. As Falcon is a [WSGI](https://www.python.org/dev/peps/pep-3333/) (and soon ASGI too) application framework, it has no access to the underlying socket transport -- that is abstracted away by the WSGI protocol. `falcon-require-https` only provides a middleware component for sanity-checking that the incoming request was received over HTTPS, based on the information it receives from the application server.

The same applies to [using `falcon-require-https` with a Hug application](https://github.com/hugapi/hug/issues/865), as Hug is also a WSGI framework (that is based on Falcon).

You'll have to either configure your WSGI server to support SSL, or deploy it behind a front-end proxy/load balancer that is capable of SSL termination.
